C-client:
  - changed-files:
      - any-glob-to-any-file: client/**
C-integration_test:
  - changed-files:
      - any-glob-to-any-file: integration_test/**
C-jsonrpc:
  - changed-files:
      - any-glob-to-any-file: jsonrpc/**
C-node:
  - changed-files:
      - any-glob-to-any-file: node/src/lib.rs
C-types:
  - changed-files:
      - any-glob-to-any-file: types/**
C-verify:
  - changed-files:
      - any-glob-to-any-file: verify/**
