// SPDX-License-Identifier: CC0-1.0

//! Auto-generated client bindings for Bitcoin Core `30`, split by API section.
//!
//! Generated by `codegen`. Do not edit any file in this module by hand.
//! Re-run `just codegen` from the workspace root to regenerate.
//!
//! Each module adds an `impl Client` block of method wrappers plus the `*Options` request
//! structs for that section. The response types live in the `corepc-types` crate
//! (`types::v30::generated`).

#![allow(unused_imports)]

pub mod blockchain;
pub mod control;
pub mod mining;
pub mod network;
pub mod raw_transactions;
pub mod signer;
pub mod util;
pub mod wallet;

pub use self::blockchain::*;
pub use self::control::*;
pub use self::mining::*;
pub use self::network::*;
pub use self::raw_transactions::*;
pub use self::signer::*;
pub use self::util::*;
pub use self::wallet::*;
